apiVersion: v1
kind: Secret
metadata:
  name: fcg-users-api-secret
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: Host=fcg-postgres;Port=5432;Database=fcg_users;Username=postgres;Password=postgres
  MessageBusConfigs__Host: amqp://admin:admin@fcg-rabbitmq:5672/
  Jwt__Key: rN8#kL2vQ9@xT5mP1!zC7$dH4^bW6&yU